from enum import Enum


class ErrorCode(Enum):
    DECISION_EXPLANATION_EMPTY = "DECISION_EXPLANATION_EMPTY"
    DECISION_NOT_FOUND = "DECISION_NOT_FOUND"
    DECISION_OUTCOME_INVALID = "DECISION_OUTCOME_INVALID"
    EVENT_FIELD_EMPTY = "EVENT_FIELD_EMPTY"
    EVENT_FIELD_INVALID = "EVENT_FIELD_INVALID"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_PAYLOAD_EMPTY = "EVENT_PAYLOAD_EMPTY"
    EVENT_TIMESTAMP_INVALID = "EVENT_TIMESTAMP_INVALID"
    EVENT_TYPE_EMPTY = "EVENT_TYPE_EMPTY"
    RULE_CONDITION_INVALID = "RULE_CONDITION_INVALID"
    RULE_CONDITION_OPERATOR_EMPTY = "RULE_CONDITION_OPERATOR_EMPTY"
    RULE_CONDITION_OPERATOR_INVALID = "RULE_CONDITION_OPERATOR_INVALID"
    RULE_CONDITION_VALUE_EMPTY = "RULE_CONDITION_VALUE_EMPTY"
    RULE_NAME_EMPTY = "RULE_NAME_EMPTY"
    RULE_OUTCOME_EMPTY = "RULE_OUTCOME_EMPTY"
    RULE_NOT_FOUND = "RULE_NOT_FOUND"
