from enum import Enum


class ErrorCode(Enum):
    CONDITION_INVALID = "CONDITION_INVALID"
    CONDITION_MISSING_FIELDS = "CONDITION_MISSING_FIELDS"
    CONDITION_OPERATOR_EMPTY = "CONDITION_OPERATOR_EMPTY"
    CONDITION_OPERATOR_INVALID = "CONDITION_OPERATOR_INVALID"
    CONDITION_TYPE_INVALID = "CONDITION_TYPE_INVALID"
    CONDITION_VALUE_EMPTY = "CONDITION_VALUE_EMPTY"
    DECISION_NOT_FOUND = "DECISION_NOT_FOUND"
    DECISION_OUTCOME_INVALID = "DECISION_OUTCOME_INVALID"
    EVENT_FIELD_EMPTY = "EVENT_FIELD_EMPTY"
    EVENT_FIELD_INVALID = "EVENT_FIELD_INVALID"
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_OCCURRED_AT_INVALID = "EVENT_OCCURRED_AT_INVALID"
    EVENT_PAYLOAD_EMPTY = "EVENT_PAYLOAD_EMPTY"
    EVENT_TYPE_EMPTY = "EVENT_TYPE_EMPTY"
    RULE_NAME_EMPTY = "RULE_NAME_EMPTY"
    RULE_OUTCOME_EMPTY = "RULE_OUTCOME_EMPTY"
    RULE_PRIORITY_INVALID = "RULE_PRIORITY_INVALID"
    RULE_NOT_FOUND = "RULE_NOT_FOUND"
